classDiagram
class Enclst {
title: String
url: String
items: List<Item>
createFromURL(): Enclst
nextEnclst(): void
}
class Item 
title: String
value: Value

Item ..> Value
class Value 
positionalValues: List<String>
namedValues: Map<String, String>

